### PR TITLE
This much delay is okay I think

### PR DESCRIPTION
**Pull request by thekunalsaini**
Working

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Your description is a bit short. Why do you think this delay needs to be changed? Also, "is okay I think" is a bit of thin rationale, what defines "okay"?

**Comment by thekunalsaini** [comment]
I m trying to say that this number represents the time in milliseconds the program has to wait until moving on to the next line of code so this much time is okay for correct execution of program.

**Comment by thekunalsaini** [comment]
@matthijskooijman

**Comment by matthijskooijman** [comment]
And the old value was not okay?

**Comment by matthijskooijman** [comment]
Don't get me wrong - It's great that you're contributing to improve things, but to help with reviewing changes (and also, to help with understanding changes when looking at the git history later), it is important to document *why* things are changing, whether there are problems fixed, etc. Sometimes things are just a little bit nicer, cleaner, prettier without actually fixing something that was broken, but then it is good to make that explicit as well :-)

**Comment by thekunalsaini** [comment]
yeah it was fine thanks I closing pull request

**Pull request closed without merging**
