### PR TITLE
Fix compiler warnings about ignored 'const' in EEPROM.h

### PR DESCRIPTION
**Pull request by bxparks**
Fix for Issue #36

### CODE REVIEW

**Comment by per1234** [comment]
Fixes https://github.com/arduino/Arduino/issues/3783

**Comment by facchinm** [comment]
LGTM! Does it solve the issue for both 4.9 (AVR core 1.6.19) and 5.4 (AVR core 1.6.20) compilers?

**Comment by per1234** [comment]
@bxparks Arduino IDE 1.8.6's bundled Arduino AVR Boards 1.6.22 uses avr-gcc ['5.4.0-atmel3.6.1-arduino2](https://github.com/arduino/Arduino/blob/master/hardware/package_index_bundled.json#L56). Arduino AVR Boards 1.6.22 hasn't been released separately from the IDE so that's why you don't see it in https://downloads.arduino.cc/packages/package_index.json. Perhaps facchinm got the version number mixed up.

**Comment by bxparks** [comment]
Ah, it was released a few days ago.
I installed IDE 1.8.6 and verified my PR fixes the warning in avr-gcc 5.4.0-atmel3.6.1-arduino2 (core 1.6.22) as well.

**Comment by facchinm** [comment]
Yes, I meant 1.6.22, sorry for the confusion.

**Pull request merged**
